version: "3"
services:
  www:
    image: nginx:alpine
    container_name: base_nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx/
      - ./:/usr/share/nginx/html

  php-fpm:
    container_name: base_php-fpm
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/logs:/var/log/php
      - ./:/usr/share/nginx/html

  db:
    image: postgres
    container_name: base_db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: base
    volumes:
    - .docker/db/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
